"use client";

import { useRouter } from "next/navigation";
import styles from "./privacy-policy.module.css";
import { FaArrowLeft } from "react-icons/fa";

export default function PrivacyPolicy() {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <button onClick={() => router.back()} className={styles.backButton}>
        <FaArrowLeft /> Back
      </button>
      <div className={styles.content}>
        <h1>Privacy Policy</h1>
        <p className={styles.lastUpdated}>Updated at 2025-05-25</p>

        <div className={styles.policyContent}>
          <p>Sempai HQ ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Sempai HQ.</p>
          
          <p>This Privacy Policy applies to our website, and its associated subdomains (collectively, our "Service") alongside our application, Sempai HQ. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service. This Privacy Policy was created with Termify.</p>

          <h2>Definitions and key terms</h2>
          <p>To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:</p>
          <ul>
            <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
            <li><strong>Company:</strong> when this policy mentions "Company," "we," "us," or "our," it refers to Sempai HQ, that is responsible for your information under this Privacy Policy.</li>
            <li><strong>Country:</strong> where Sempai HQ or the owners/founders of Sempai HQ are based, in this case is Nigeria</li>
            <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the Sempai HQ Service to manage the relationships with your consumers or service users.</li>
            <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Sempai HQ and use the services.</li>
            <li><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
            <li><strong>Personnel:</strong> refers to those individuals who are employed by Sempai HQ or are under contract to perform a service on behalf of one of the parties.</li>
            <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
            <li><strong>Service:</strong> refers to the service provided by Sempai HQ as described in the relative terms (if available) and on this platform.</li>
            <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
            <li><strong>Website:</strong> Sempai HQ's site, which can be accessed via this URL: https://sempaihq.xyz</li>
            <li><strong>You:</strong> a person or entity that is registered with Sempai HQ to use the Services.</li>
          </ul>

          <h2>What Information Do We Collect?</h2>
          <p>We collect information from you when you visit our website/app, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.</p>
          <ul>
            <li>Name / Username</li>
            <li>Email Addresses</li>
          </ul>

          <h2>How Do We Use The Information We Collect?</h2>
          <p>Any of the information we collect from you may be used in one of the following ways:</p>
          <ul>
            <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
            <li>To improve our website/app (we continually strive to improve our website/app offerings based on the information and feedback we receive from you)</li>
            <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
            <li>To process transactions</li>
            <li>To administer a contest, promotion, survey or other site feature</li>
            <li>To send periodic emails</li>
          </ul>

          <h2>When does Sempai HQ use end user information from third parties?</h2>
          <p>Sempai HQ will collect End User Data necessary to provide the Sempai HQ services to our customers. End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</p>

          <h2>When does Sempai HQ use customer information from third parties?</h2>
          <p>We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming a Sempai HQ customer, we receive information from a third party that provides automated fraud detection services to Sempai HQ. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</p>

          <h2>Do we share the information we collect with third parties?</h2>
          <p>We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.</p>

          <h2>Where and when is information collected from customers and end users?</h2>
          <p>Sempai HQ will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.</p>

          <h2>How Do We Use Your Email Address?</h2>
          <p>By submitting your email address on this website/app, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do.</p>

          <h2>How Long Do We Keep Your Information?</h2>
          <p>We keep your information only so long as we need it to provide Sempai HQ to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we'll either remove it from our systems or depersonalize it so that we can't identify you.</p>

          <h2>How Do We Protect Your Information?</h2>
          <p>We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential.</p>

          <h2>Could my information be transferred to other countries?</h2>
          <p>Sempai HQ is incorporated in Nigeria. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information.</p>

          <h2>Is the information collected through the Sempai HQ Service secure?</h2>
          <p>We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.</p>

          <h2>Sale of Business</h2>
          <p>We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of Sempai HQ or any of its Corporate Affiliates (as defined herein), or that portion of Sempai HQ or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.</p>

          <h2>Affiliates</h2>
          <p>We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with Sempai HQ, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.</p>

          <h2>Governing Law</h2>
          <p>This Privacy Policy is governed by the laws of Nigeria without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.</p>

          <h2>Changes To This Privacy Policy</h2>
          <p>We reserve the right to modify this Privacy Policy at any time. If we make material changes to this policy, we may notify you on our Website, by a blog post, by email, or by any method we determine. The method we chose is at our sole discretion. We will also change the "Last Updated" date at the beginning of this Privacy Policy. Any changes we make to our Privacy Policy are effective as of this Last Updated date and replace any prior Privacy Policies.</p>

          <h2>Questions About Our Privacy Practices or This Privacy Policy</h2>
          <p>If you have any questions about our Privacy Practices or this Policy, please contact us.</p>

          <h2>Contact Us</h2>
          <p>Don't hesitate to contact us if you have any questions.</p>
          <p>Via Email: gregboy76@gmail.com</p>
          <p>Via Phone Number: +234 8163731843</p>
          <p>Via this Address: 9, Irepodun Street, Alaagba, Iyana-Ipaja Lagos, Nigeria</p>
        </div>
      </div>
    </div>
  );
} 